### ISSUE TITLE
Not working in Pharo 12

### ISSUE THREAD

**Issue by astares** [yannij/Seaside-Quasar#2]
Using the load script from README does not work in Pharo 12. It does not even load Seaside. 

I think the referenced Seaside version should be updated to [v3.5.7](https://github.com/SeasideSt/Seaside/releases/tag/v3.5.7)

**Comment by yannij** [comment]
The load works now, using the code in the README. I suspect there was a problem with Grease (now fixed) where a floating version was pulled in that would work with Pharo12, but would not work with an older version of Seaside.
